/**
 * Every record managed by sync-subscribe must include these base fields.
 */
export interface SyncRecord {
  /** Unique identifier for this record within its collection. */
  recordId: string;
  createdAt: number; // unix ms
  updatedAt: number; // unix ms — client stores local time, server stores server time
  revisionCount: number; // incremented on every mutation; used for conflict resolution
}

/**
 * A filter expression used to define what data a subscription covers.
 * Keys are record field names; values are the required values (equality match).
 *
 * More complex operators (gt, lt, in, …) will be added in future iterations.
 */
export type FilterValue = string | number | boolean | null;

export type FilterOperator =
  | { $gt: FilterValue }
  | { $gte: FilterValue }
  | { $lt: FilterValue }
  | { $lte: FilterValue }
  | { $ne: FilterValue };

export type FilterCondition = FilterValue | FilterOperator;

export type SubscriptionFilter = Record<string, FilterCondition>;

/**
 * Opaque token generated by the server to track sync progress.
 * Clients must treat this as a black box and send it back verbatim.
 * Internally it encodes: updatedAt + revisionCount + recordId of the last
 * synced record for a given subscription.
 */
export type SyncToken = string & { readonly __brand: "SyncToken" };

/** Sentinel for a client that has never synced. */
export const EMPTY_SYNC_TOKEN = "" as SyncToken;

export interface Subscription {
  subscriptionId: string;
  filter: SubscriptionFilter;
  syncToken: SyncToken;
}

/**
 * A patch sent from server → client describing a single record change.
 */
export type SyncPatch<T extends SyncRecord> =
  | { op: "upsert"; record: T }
  | { op: "delete"; recordId: string };

/**
 * Conflict resolution result returned when a client push conflicts with
 * a more-recent server record.
 */
export interface ConflictResult<T extends SyncRecord> {
  conflict: true;
  serverRecord: T;
}
