/**
 * Every record managed by sync-subscribe must include these base fields.
 */
export interface SyncRecord {
  /** Unique identifier for this record within its collection. */
  recordId: string;
  createdAt: number; // unix ms
  updatedAt: number; // unix ms — client stores local time, server stores server time
  revisionCount: number; // incremented on every mutation; used for conflict resolution
  /** Index signature so that T extends SyncRecord satisfies Record<string, unknown>. */
  [key: string]: unknown;
}

import type { Query } from "sift";

/**
 * Primitive value used in filter conditions and SQL conversion.
 */
export type FilterValue = string | number | boolean | null;

/**
 * A sift-compatible MongoDB-style query filter, typed against a plain object.
 *
 * Supports the full sift operator set: $eq, $ne, $gt, $gte, $lt, $lte,
 * $in, $nin, $or, $and, $nor, $not, $exists, $regex, and more.
 *
 * @example
 * { color: "blue" }
 * { createdAt: { $gte: Date.now() - 86400000 } }
 * { $or: [{ color: "blue" }, { color: "red" }] }
 */
export type SubscriptionFilter<
  T extends Record<string, unknown> = Record<string, unknown>,
> = Query<T>;

/**
 * Opaque token generated by the server to track sync progress.
 * Clients must treat this as a black box and send it back verbatim.
 * Internally it encodes: updatedAt + revisionCount + recordId of the last
 * synced record for a given subscription.
 */
export type SyncToken = string & { readonly __brand: "SyncToken" };

/** Sentinel for a client that has never synced. */
export const EMPTY_SYNC_TOKEN = "" as SyncToken;

export interface Subscription {
  subscriptionId: string;
  filter: SubscriptionFilter;
  syncToken: SyncToken;
}

/**
 * A patch sent from server → client describing a single record change.
 */
export type SyncPatch<T extends SyncRecord> =
  | { op: "upsert"; record: T }
  | { op: "delete"; recordId: string };

/**
 * Conflict resolution result returned when a client push conflicts with
 * a more-recent server record.
 */
export interface ConflictResult<T extends SyncRecord> {
  conflict: true;
  serverRecord: T;
}
